
Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-54bs9[0m
{"level":"warn","ts":1572689684.9734237,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572689684.9743586,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-htqh2[0m
{"level":"warn","ts":1572689686.0375314,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1572689686.0414505,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-marthydavid-python-own-demo-mas-zz8f4[0m
{"level":"warn","ts":1572689692.1879044,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572689694.1453283,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/***********/python-own-demo.git @ v0.0.4 in path /workspace/source"}
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:b0169e3245310e0e0381458c52115c8fb0af4c1d
WARNING: no SHAs to merge, falling back to initial cloned commit
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2019/11/02 10:14:55 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:onbuild        
2019/11/02 10:14:57 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Executing 3 build triggers                   
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] Checking for cached layer docker-registry.**.k8s2.marthy.xyz/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
2019/11/02 10:14:58 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] Skipping unpacking as no commands require it. 
[36mINFO[0m[0003] Taking snapshot of full filesystem...        
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0003] Found cached layer, extracting to filesystem 
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] COPY . /usr/src/app                          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt .                      
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] ENV PORT 8080                                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] EXPOSE 8080                                  
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] ENTRYPOINT ["python"]                        
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] CMD ["app.py"]                               
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
2019/11/02 10:14:58 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2019/11/02 10:14:58 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2019/11/02 10:14:58 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2019/11/02 10:14:58 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2019/11/02 10:14:58 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2019/11/02 10:14:58 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2019/11/02 10:14:58 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2019/11/02 10:14:58 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2019/11/02 10:14:58 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2019/11/02 10:14:59 pushed blob: sha256:18b51b787c54966a3f386978df7218200f7c8faab87c6a29fc2c6d7a9e95cd48
2019/11/02 10:14:59 pushed blob: sha256:53d9b8b8d25fa0ba9387ffdef723e53be9bed0d3d88fea5a7f5188c417a60ba6
2019/11/02 10:14:59 pushed blob: sha256:13dd0107d3dd7eaa9c8fda9873f3d3cc451e37842b6a924b3d1bbf95cf7e2eee
2019/11/02 10:14:59 pushed blob: sha256:e304c27f465e9e29b2129381e94e461e343672b1b74d1aa40b8a1ed319e19299
2019/11/02 10:14:59 pushed blob: sha256:ac4df4f16b4e73972dcd8c6f7c48793ae1f6768cb9c6969062901af16c843533
2019/11/02 10:14:59 docker-registry.**.k8s2.marthy.xyz/***********/python-own-demo:0.0.4: digest: sha256:ca880b6e2fdc1aba1737fe5296894e64c90e12b9c7352bcda2e29866c213554f size: 2385
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/python-own-demo to an unshallow repository
Generating change log from git ref a5a87fc83681270a81d0cb9ef1ca30101f95dea5 => dee00d80d24fd9be5a94fc4ae3bc696346f3564a
Associating user *********** in users.jenkins.io with email marthy.david@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user *********** in users.jenkins.io
WARNING: Failed to enrich commit 472f2c27aaf16e7d41c104e3095bdaddd9db521a with issues: User.jenkins.io "***********" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user *********** in users.jenkins.io with email marthy.david@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user *********** in users.jenkins.io
WARNING: Failed to enrich commit 472f2c27aaf16e7d41c104e3095bdaddd9db521a with issues: User.jenkins.io "***********" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
Associating user *********** in users.jenkins.io with email marthy.david@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user *********** in users.jenkins.io
WARNING: Failed to enrich commit 63538001ed7107ad68ef2686526c5a2d7bd8ff3a with issues: User.jenkins.io "***********" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user *********** in users.jenkins.io with email marthy.david@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user *********** in users.jenkins.io
WARNING: Failed to enrich commit 63538001ed7107ad68ef2686526c5a2d7bd8ff3a with issues: User.jenkins.io "***********" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
WARNING: No release found for ***********/python-own-demo and tag v0.0.4 so creating a new release
Updated the release information at https://github.com/***********/python-own-demo/releases/tag/v0.0.4
generated: /workspace/source/charts/python-own-demo/templates/release.yaml
Created Release python-own-demo-0-0-4 resource in namespace **
Updating PipelineActivity ***********-python-own-demo-master-4 with version 0.0.4
Updated PipelineActivities ***********-python-own-demo-master-4 with release notes URL: https://github.com/***********/python-own-demo/releases/tag/v0.0.4
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file python-own-demo-0.0.4.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}
failed to create fsnotify watcher: too many open files

Showing logs for build [32mmarthydavid-python-own-demo-mas-vhst2-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app python-own-demo version 0.0.4 to namespace **-staging
Created Pull Request: https://github.com/***********/environment-kittenshadow-staging/pull/1
Added label updatebot to Pull Request https://github.com/***********/environment-kittenshadow-staging/pull/1
WARNING: Failed to query the Pull Request last commit status for https://github.com/***********/environment-kittenshadow-staging/pull/1 ref 351931220433de8120452b31ed426751f087cd7d Could not find a status for repository ***********/environment-kittenshadow-staging with ref 351931220433de8120452b31ed426751f087cd7d
Pull Request https://github.com/***********/environment-kittenshadow-staging/pull/1 is merged at sha 7cf55089c0bbacd01b3340674557954263bf4cdc
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-staging for names python-own-demo, **-python-own-demo, **-staging-python-own-demo
failed to create fsnotify watcher: too many open files
